### ISSUE TITLE
Permission denied when making /.cache.

### ISSUE THREAD

**Issue by Robin-Rounthwaite** [jmonlong/sveval#20]
I pulled the latest docker container for 2.2.0, and the snakemake keywords work now. But when I run snakemake, I run into a new issue with the automated creation of the `/.cache` directory.

```
rrounthw@mustard:/private/groups/patenlab/rrounthw/sveval/snakemake$ docker run -it --rm -v `pwd`:/app -w /app -u `id -u $USER` quay.io/jmon
long/sveval:v2.2.0
I have no name!@abbc525abd6f:/app$ snakemake --configfile config.yaml --cores 4
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/snakemake/__init__.py", line 595, in snakemake
    workflow = Workflow(
  File "/usr/local/lib/python3.8/dist-packages/snakemake/workflow.py", line 232, in __init__
    self.sourcecache = SourceCache()
  File "/usr/local/lib/python3.8/dist-packages/snakemake/sourcecache.py", line 353, in __init__
    os.makedirs(self.cache, exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/.cache'
```

**Comment by jmonlong** [comment]
Sorry, I didn't realize the new version used a `.cache` folder and that it was not accessible in the container. I've updated the docker container and tested it, so it should work now.
